In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv("MENTAL HEALTH DATA.csv")
data.head()

data.general_health.nunique()

,year_1,state_1,general_health,phq9_1,phq9_2,phq9_3,phq9_4,phq9_5,phq9_6,phq9_7,phq9_8,phq9_9,phq9_1NUM,phq9_2NUM,phq9_3NUM,phq9_4NUM,phq9_5NUM,phq9_6 NUM,phq9_7NUM,phq9_8NUM,phq9_9NUM,phq9_COMP,phq9_severity,gad7_1,gad7_2,gad7_3,gad7_4,gad7_5,gad7_6,gad7_7,gad7_1NUM,gad7_2NUM,gad7_3NUM,gad7_4NUM,gad7_5NUM,gad7_6NUM,gad7_7NUM,gad7_COMP,gad7_severity,acha_12months_times_1,acha_12months_times_2,acha_12months_times_3,acha_12months_times_4,acha_12months_times_5,acha_12months_times_6,acha_12months_times_7,acha_depression,acha_services_1,acha_services_2,acha_services_3,acha_12months_any_1,acha_12months_any_2,acha_12months_any_3,acha_12months_any_4,acha_12months_any_5,acha_12months_any_6,acha_12months_any_7,acha_12months_any_8,acha_12months_any_9,acha_12months_any_10,acha_12months_any_11,acha_12months_any_12,acha_12months_any_13,acha_12months_any_14,acha_12months_any_15,acha_12months_any_16,acha_12months_any_17,acha_12months_any_18,acha_12months_any_19,acha_12months_any_20,acha_12months_any_21,acha_12months_any_22,acha_12months_any_23,acha_12months_any_24,acha_12months_any_25,acha_12months_any_26,acha_12months_any_27,acha_12months_any_28,acha_12months_any_29,acha_12months_any_1NUM,acha_12months_any_2NUM,acha_12months_any_3NUM,acha_12months_any_4NUM,acha_12months_any_5NUM,acha_12months_any_6NUM,acha_12months_any_7NUM,acha_12months_any_8NUM,acha_12months_any_9NUM,acha_12months_any_10NUM,acha_12months_any_11NUM,acha_12months_any_12NUM,acha_12months_any_13NUM,acha_12months_any_14NUM,acha_12months_any_15NUM,acha_12months_any_16NUM,acha_12months_any_17NUM,acha_12months_any_18NUM,acha_12months_any_19NUM,acha_12months_any_20NUM,acha_12months_any_21NUM,acha_12months_any_22NUM,acha_12months_any_23NUM,acha_12months_any_24NUM,acha_12months_any_25NUM,acha_12months_any_26NUM,acha_12months_any_27NUM,acha_12months_any_28NUM,acha_12months_any_29NUM,acha_12months_any_comp,sex,fulltime,international,race_1,race_2,race_3,race_4,race_5,race_6
0,2000,MD,Very Good,Several days,Several days,Not at all,Several days,Not at all,Not at all,More than half of the days,Not at all,Several days,1,1,0,1,0,0,2,0,1,6,Mild depression,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,0,0,0,0,0,0,0,0,minimal anxiety,Never,11 or more times,5-6 times,3-4 times,Never,Never,Never,No,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,No,No,No,No,No,No,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,2,Female,Yes,No,NaN,NaN,NaN,Asian or Pacific Islander,NaN,NaN
1,2001,SC,Good,More than half of the days,More than half of the days,Nearly every day,Nearly every day,Nearly every day,Several days,Nearly every day,Several days,Several days,2,2,3,3,3,1,3,1,1,19,Moderately severe depression,Several days,Not at all,Not at all,Not at all,Not at all,More than half of the days,Several days,1,0,0,0,0,2,1,4,minimal anxiety,1-2 times,5-6 times,7-8 times,1-2 times,1-2 times,1-2 times,Never,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Female,Yes,No,NaN,NaN,NaN,Asian or Pacific Islander,NaN,NaN
2,1999,NJ,Good,Several days,Several days,More than half of the days,More than half of the days,Several days,Several days,Several days,Several days,Not at all,1,1,2,2,1,1,1,1,0,10,Moderate depression,Several days,More than half of the days,More than half of the days,Several days,Not at all,Nearly every day,Not at all,1,2,2,1,0,3,0,9,mild anxiety,7-8 times,11 or more times,11 or more times,9-10 times,1-2 times,Never,Never,No,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Yes,No,No,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,2,Female,Yes,No,NaN,NaN,Hispanic or Latino,Asian or Pacific Islander,NaN,NaN
3,1998,NY,Good,Several days,Several days,Nearly every day,Nearly every day,Not at all,Several days,Several days,Several days,Not at all,1,1,3,3,0,1,1,1,0,11,Moderate depression,More than half of the days,Several days,More than half of the days,Several days,Several days,More than half of the days,Several days,2,1,2,1,1,2,1,10,moderate anxiety,9-10 times,9-10 times,7-8 times,11 or more times,3-4 times,Never,Never,No,NaN,NaN,NaN,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,Female,Yes,No,White - not Hispanic (includes Middle Eastern),NaN,NaN,NaN,NaN,NaN
4,2000,PA,Very Good,Not at all,Several days,Several days,Several days,Several days,Several days,Several days,Not at all,Not at all,0,1,1,1,1,1,1,0,0,6,Mild depression,Nearly every day,Nearly every day,Nearly every day,Nearly every day,More than half of the days,Nearly every day,Several days,3,3,3,3,2,3,1,18,severe anxiety,7-8 times,3-4 times,9-10 times,11 or more times,1-2 times,Never,Never,No,NaN,NaN,NaN,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,Yes,No,No,No,No,No,No,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,5,Female,Yes,No,White - not Hispanic (includes Middle Eastern),NaN,NaN,NaN,NaN,NaN

5

In [3]:
data.describe()

,year_1,phq9_1NUM,phq9_2NUM,phq9_3NUM,phq9_4NUM,phq9_5NUM,phq9_6 NUM,phq9_7NUM,phq9_8NUM,phq9_9NUM,phq9_COMP,gad7_1NUM,gad7_2NUM,gad7_3NUM,gad7_4NUM,gad7_5NUM,gad7_6NUM,gad7_7NUM,gad7_COMP,acha_12months_any_1NUM,acha_12months_any_2NUM,acha_12months_any_3NUM,acha_12months_any_4NUM,acha_12months_any_5NUM,acha_12months_any_6NUM,acha_12months_any_7NUM,acha_12months_any_8NUM,acha_12months_any_9NUM,acha_12months_any_10NUM,acha_12months_any_11NUM,acha_12months_any_12NUM,acha_12months_any_13NUM,acha_12months_any_14NUM,acha_12months_any_15NUM,acha_12months_any_16NUM,acha_12months_any_17NUM,acha_12months_any_18NUM,acha_12months_any_19NUM,acha_12months_any_20NUM,acha_12months_any_21NUM,acha_12months_any_22NUM,acha_12months_any_23NUM,acha_12months_any_24NUM,acha_12months_any_25NUM,acha_12months_any_26NUM,acha_12months_any_27NUM,acha_12months_any_28NUM,acha_12months_any_29NUM,acha_12months_any_comp
count,579.000000,579.00000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.000000,579.00000
mean,1998.398964,1.02418,1.065630,1.343696,1.568221,1.226252,1.122625,1.188256,0.438687,0.395509,9.373057,1.462867,1.196891,1.381693,1.281520,0.891192,1.214162,0.896373,8.324698,0.386874,0.074266,0.483592,0.131261,0.032815,0.075993,0.426598,0.017271,0.022453,0.013817,0.008636,0.005181,0.067358,0.060449,0.001727,0.062176,0.160622,0.072539,0.424870,0.020725,0.041451,0.017271,0.063903,0.005181,0.012090,0.005181,0.193437,0.084629,0.003454,2.97582
std,5.403260,0.90334,0.935189,0.998792,0.968407,1.043484,1.042599,1.017562,0.765354,0.767448,6.200711,0.959339,1.045301,1.032890,0.995763,0.954089,0.949817,0.984115,5.685068,0.487456,0.262430,0.500163,0.337977,0.178307,0.265216,0.495010,0.130393,0.148278,0.116831,0.092606,0.071857,0.250857,0.238523,0.041559,0.241684,0.367499,0.259602,0.494751,0.142587,0.199503,0.130393,0.244792,0.071857,0.109381,0.071857,0.395334,0.278569,0.058722,2.48374
min,1971.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,1998.000000,0.00000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000
50%,2000.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.00000
75%,2001.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,13.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,1.000000,12.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.00000
max,2003.000000,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,27.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,28.00000

In [7]:
data.columns

data.shape

Index(['year_1', 'state_1', 'general_health', 'phq9_1', 'phq9_2', 'phq9_3',
       'phq9_4', 'phq9_5', 'phq9_6', 'phq9_7',
       ...
       'acha_12months_any_comp', 'sex', 'fulltime', 'international', 'race_1',
       'race_2', 'race_3', 'race_4', 'race_5', 'race_6'],
      dtype='object', length=118)

(579, 118)

In [6]:
# SOCIODEMOGRAPHIC FEATURES
# year, sex, fulltime, international, race

vars = ["year_1", "sex", "fulltime", "international", "race_1", "race_2", "race_3", "race_4", "race_5", "race_6"]

fig = make_subplots(columns = 2)

for var in vars:
    grouped = data.groupby([var], as_index=False).size()
    fig = px.bar(grouped, x=var, y ='size')
    fig.update_layout(
    autosize=False,
    width=400,
    height=400,
    )

for trace in bar1.data: